### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by hamidreza-hosseini** [emgag/varnish-towncrier#1]
Hi,
I wanna use this tool but i dont know how can i install and use it?
I should install this tool and redis on all nodes or just the controller node and the controller forward our Purge request to other nodes?

**Comment by maetthu** [comment]
You need one centralized redis service, and for each varnish instance you need one varnish-towncrier instance as a local agent to forward commands. Like this: 
![architecture](https://user-images.githubusercontent.com/1193955/70372006-202d5380-18da-11ea-9678-6d36fa49edea.png)
